version: "3.3"
services:

  my-db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: clienteapi
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: admin1234
    ports: 
      - 3306:3306
    networks:
      - cliente-api-network

  cliente-api:
    image: nettooe/cliente-api-jvm:7.0.1
    restart: always
    build:
        context: ./
        dockerfile: src/main/docker/Dockerfile.jvm
    environment: 
        QUARKUS_DATASOURCE_KIND: mysql
        QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://my-db:3306/clienteapi
        QUARKUS_DATASOURCE_USERNAME: mysqluser
        QUARKUS_DATASOURCE_PASSWORD: admin1234
        QUARKUS_DATASOURCE_JDBC_MIN_SIZE: 1
        QUARKUS_DATASOURCE_JDBC_MAX_SIZE: 10
    ports: 
        - 8080:8080
    depends_on: 
        - my-db
    networks:
        - cliente-api-network

networks: 
  cliente-api-network:
    driver: bridge